# Generated by Django 5.0.4 on 2024-04-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='merchandiseamount',
            field=models.IntegerField(),
        ),
    ]
