# Generated by Django 4.2.11 on 2024-04-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalks', '0002_alter_merchandise_merchandiseamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchandise',
            old_name='merchandisename',
            new_name='merchandise_name',
        ),
    ]
