# Generated by Django 4.2.11 on 2024-04-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalks', '0003_rename_merchandisename_merchandise_merchandise_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchandise',
            old_name='merchandise_name',
            new_name='merchandisename',
        ),
    ]
